openapi: 3.0.2

info:
  title: Password Validator API
  version: 2.0.0

servers:
  - url: http://localhost:8080
    description: Local docker environment

paths:
  "/evaluate":
    post:
      tags:
        - Password evaluation
      summary: Evaluate a password
      description: Evaluate and response if that password is valid
      parameters:
        - in: query
          name: length
          required: false
          schema:
            $ref: "#components/schemas/LengthParam"
          description: Number of minimal length for the password
      requestBody:
        description: Raw password
        required: true
        content:
          text/plain:
            schema:
              $ref: "#components/schemas/PasswordRequest"
      responses:
        "200":
          description: Valid password
          content:
            text/plain:
              schema:
                $ref: "#components/schemas/PasswordResponse_200"
        "400":
          description: Invalid password
          content:
            text/plain:
              schema:
                $ref: "#components/schemas/PasswordResponse_400"

components:
  schemas:
    LengthParam:
      type: int
      description: Number of minimal length for the password
      example: 9
    PasswordRequest:
      type: string
      description: Raw password
      example: A!1qwe
    PasswordResponse_200:
      type: boolean
      description: Valid password
      example: true
    PasswordResponse_400:
      type: boolean
      description: Invalid password
      example: false